### ISSUE TITLE
SetTx() missing

### ISSUE THREAD

**Issue by eadmaster** [angrest/SmartCC1101#4]
maybe is it intentional?

**Comment by angrest** [comment]
This is entirely intentional. 
the moment you call sendData(), the chip is set to TX and returns to idle as soon as the transmission is complete. 
on the other hand, setRX() is needed as a transmission could come in any time and the program should be able to signal the chip when it attends incoming data.

**Comment by eadmaster** [comment]
for context, we have an use case [here](https://github.com/pr3y/Bruce/blob/main/src/modules/rf/rf.cpp#L669) were we want to write directly raw signals to the `GDO0` pin. Without a `setTx()` method this cannot be done.

**Comment by angrest** [comment]
Ok, well - I do not use any `GDO` based stuff internally. It would be easy to add a `setTX()` function, but I doubt that the rest of the code would fit your requirements.
